// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8DZCZgXH3W1DRjLDuyfSLhKtjYroYW6w',
    appId: '1:932385263341:web:79d74446fc8a3c08d786e4',
    messagingSenderId: '932385263341',
    projectId: 'kutso-b90c7',
    authDomain: 'kutso-b90c7.firebaseapp.com',
    storageBucket: 'kutso-b90c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8wdFsLy6v0ekIWIjPCIS9Q-BtRgGDI98',
    appId: '1:932385263341:android:d973e0c6fda229b2d786e4',
    messagingSenderId: '932385263341',
    projectId: 'kutso-b90c7',
    storageBucket: 'kutso-b90c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwD9xwd1oDmPAN8ZpTOJR6dqVLdaCVDYQ',
    appId: '1:932385263341:ios:66f87ccfa98652e1d786e4',
    messagingSenderId: '932385263341',
    projectId: 'kutso-b90c7',
    storageBucket: 'kutso-b90c7.appspot.com',
    iosBundleId: 'com.example.pz26',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwD9xwd1oDmPAN8ZpTOJR6dqVLdaCVDYQ',
    appId: '1:932385263341:ios:66f87ccfa98652e1d786e4',
    messagingSenderId: '932385263341',
    projectId: 'kutso-b90c7',
    storageBucket: 'kutso-b90c7.appspot.com',
    iosBundleId: 'com.example.pz26',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8DZCZgXH3W1DRjLDuyfSLhKtjYroYW6w',
    appId: '1:932385263341:web:a5725cb76c29cbc3d786e4',
    messagingSenderId: '932385263341',
    projectId: 'kutso-b90c7',
    authDomain: 'kutso-b90c7.firebaseapp.com',
    storageBucket: 'kutso-b90c7.appspot.com',
  );
}
