// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2L05gMw8iEb_-o2J-SUXkYerb6BCZaI4',
    appId: '1:1025092034044:web:4fef47907cba5b026ae679',
    messagingSenderId: '1025092034044',
    projectId: 'oda123-6ae53',
    authDomain: 'oda123-6ae53.firebaseapp.com',
    storageBucket: 'oda123-6ae53.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3UT-QDRwrKl5zUg2O11Wf5S4T6xEFZT8',
    appId: '1:1025092034044:android:962133c26316fa046ae679',
    messagingSenderId: '1025092034044',
    projectId: 'oda123-6ae53',
    storageBucket: 'oda123-6ae53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBx3TjDWZOOad3SI13F3toEAFxx-E-WrU',
    appId: '1:1025092034044:ios:c69f64620a7501106ae679',
    messagingSenderId: '1025092034044',
    projectId: 'oda123-6ae53',
    storageBucket: 'oda123-6ae53.appspot.com',
    iosBundleId: 'com.example.pz26',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBx3TjDWZOOad3SI13F3toEAFxx-E-WrU',
    appId: '1:1025092034044:ios:c69f64620a7501106ae679',
    messagingSenderId: '1025092034044',
    projectId: 'oda123-6ae53',
    storageBucket: 'oda123-6ae53.appspot.com',
    iosBundleId: 'com.example.pz26',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2L05gMw8iEb_-o2J-SUXkYerb6BCZaI4',
    appId: '1:1025092034044:web:263c28af42f7ea926ae679',
    messagingSenderId: '1025092034044',
    projectId: 'oda123-6ae53',
    authDomain: 'oda123-6ae53.firebaseapp.com',
    storageBucket: 'oda123-6ae53.appspot.com',
  );
}
